# permissions for end users to view hooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hook-viewer-role
rules:
- apiGroups:
  - cloud.lilqcn
  resources:
  - hooks
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - cloud.lilqcn
  resources:
  - hooks/status
  verbs:
  - get
