# permissions for end users to edit hooks.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: hook-editor-role
rules:
- apiGroups:
  - cloud.lilqcn
  resources:
  - hooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.lilqcn
  resources:
  - hooks/status
  verbs:
  - get
