apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: jobs-role
rules:
  - apiGroups: ["*"]
    resources: ["jobs"]
    verbs: ["get", "watch", "list", "create", "update", "patch", "delete"]
  - apiGroups: [ "*" ]
    resources: [ "jobs/status" ]
    verbs: ["get"]