apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: jobs-rolebinding
subjects:
  - kind: ServiceAccount
    name: controller-manager
    namespace: system
roleRef:
  kind: ClusterRole
  name: jobs-role
  apiGroup: rbac.authorization.k8s.io