
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  creationTimestamp: null
  name: manager-role
rules:
- apiGroups:
  - cloud.lilqcn
  resources:
  - hooks
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - cloud.lilqcn
  resources:
  - hooks/finalizers
  verbs:
  - update
- apiGroups:
  - cloud.lilqcn
  resources:
  - hooks/status
  verbs:
  - get
  - patch
  - update
