apiVersion: apps/v1
kind: Deployment
metadata:
  name: controltower-operator-hook-server
  namespace: system
  labels:
    control-plane: controller-manager
spec:
  replicas: 1
  selector:
    matchLabels:
      control-plane: controller-manager
  template:
    metadata:
      labels:
        control-plane: controller-manager
    spec:
      containers:
        - name: hook-server
          image: lilqcn/hook:0.4.16
          ports:
            - containerPort: 8080
              name: hook
        - name: smee
          image: lilqcn/smee:0.4.16
          env:
            - name: GITHUB
              valueFrom:
                configMapKeyRef:
                  name: smee-config
                  key: github_hook
            - name: DOCKERHUB
              valueFrom:
                configMapKeyRef:
                  name: smee-config
                  key: dockerhub_hook
      serviceAccountName: controller-manager